// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package webhook.sample.domain;

import org.springframework.beans.factory.annotation.Configurable;
import webhook.sample.domain.Notifications;

privileged aspect Notifications_Roo_Configurable {
    
    declare @type: Notifications: @Configurable;
    
}
